defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

production:
  <<: *defaults
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] or 'localhost' %>
  database: <%= ENV['PRODUCTION_DB_NAME'] or 'cobudget_production' %>
  username: <%= ENV['DB_USERNAME'] or 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] or '' %>